<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        const p = new Promise((resolve, reject) => {
            setTimeout(() => {
                resolve('数据')
            }, 2000)
        })
        // 调用 then方法 then方法返回的结果 result也是一个Promise对象，且对象状态由它内部回调函数的执行结果决定的
        // 1.如果内部执行的返回结果是一个 非Promise对象 的属性 ，则 then方法名为result的Promise对象状态为成功，返回结果为对象的成功值
        // 2.如果不写return 为undefined,也是非Promise对象，Promise对象状态为成功，返回结果为undefined

        // 3.如果内部执行的返回结果是一个 Promise对象 的属性 ，则 返回的这个promise对象的状态决定了then方法名为result的Promise对象状态，返回结果为then方法promise对象的值

        // 4.抛出错误 throw new Error('错误')  也是一个失败状态的promise，
        const result = p.then(value => {
            // console.log(value);
            // 1.return 123;
            return new Promise((resolve, reject) => {
                resolve('ok')
            })
            // 4.throw new Error('错误')
        })
        console.log(result);
    </script>
</body>

</html>